# Generated by Django 3.2.3 on 2021-06-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landowners', '0002_landowners_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowners',
            name='contact_number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
