# Generated by Django 3.2.3 on 2021-06-08 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landowners', '0005_auto_20210608_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landownerlistingsmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='landownerlistingsmodel',
            name='time',
        ),
        migrations.AddField(
            model_name='landownerlistingsmodel',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
