# Generated by Django 3.2.3 on 2021-06-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='landowner',
        ),
    ]
