# Generated by Django 3.2.3 on 2021-06-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
