# Generated by Django 3.2.3 on 2021-06-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_landowner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='landowner_id',
        ),
    ]
